# Project information
site_name: River
site_description: Machine learning for data streams in Python
site_author: The river developers
site_url: https://riverml.xyz

# Repository
repo_name: online-ml/river
repo_url: https://github.com/online-ml/river
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019 - 2020

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/river_square.svg
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant

# Extras
extra:
  analytics:
    provider: google
    property: UA-63302552-3
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/online-ml/river

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
      toc_depth: "1-3"
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/version-select.js

extra_css:
  - stylesheets/extra.css
  - css/version-select.css
